debug: true

db:
  dialect: "sqlite3"
  path: "kanalbot.db"

bot:
  telegram:
    debug: true
    token: "563000279:AAEmDxFLenTPNQuPiTlyMzX02sCgD79aPSQ"
    updater-timeout: 40
    session-timeout: 20
